### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by rafee** [CppMtl/Meetups#5]
When trying to execute step 2.4 on "2019-05-15 [Gabriel Aubut-Lussier, Richard Savoie] Dockerization for C++ Workshop", I get the following error:
`CMake Error: The source directory "/Sources" does not appear to contain CMakeLists.txt.`

How can I resolve this?

**Comment by Dalzhim** [comment]
Did the answer you get in the comments of the event answer your question? Was the problem solved by having the path `$(pwd)/src` inside the quotes?
